Cnv fips separate the package files to pass the scan
openshift/check-payload pull request #235
Opened 2024-12-23 12:41 UTC by tal-hason

[[payload.virt-handler-rhel9-container.ignore]]
error = "ErrNotDynLinked"
files = ["/usr/bin/container-disk"]

[[payload.virt-launcher-rhel9-container.ignore]]
error = "ErrNotDynLinked"
files = ["/usr/bin/container-disk"]

[[payload.virt-cdi-importer-rhel9-container.ignore]]
error = "ErrGoNotCgoEnabled"
files = [
  "/usr/bin/cdi-containerimage-server"
]

[[payload.kubevirt-tekton-tasks-copy-template-rhel9-container.ignore]]
error = "ErrGoNotCgoEnabled"
files = [
  "/usr/bin/kubevirt-tekton-tasks.test"
]

[[payload.kubevirt-ssp-operator-container.ignore]]
error = "ErrGoNotCgoEnabled"
files = [
  "/usr/bin/ssp-operator.test"
]

[[payload.kubevirt-tekton-tasks-copy-template-container.ignore]]
error = "ErrGoNotCgoEnabled"
files = [
  "/usr/bin/kubevirt-tekton-tasks.test"
]

[[payload.kubevirt-tekton-tasks-operator-container.ignore]]
error = "ErrGoNotCgoEnabled"
files = [
  "/usr/bin/tekton-tasks-operator.test"
]

[[payload.kubevirt-tekton-tasks-create-datavolume-rhel9-container.ignore]]
error = "ErrGoNotCgoEnabled"
files = [
  "/usr/local/bin/disk-uploader",
  "/usr/local/bin/kubevirt-tekton-tasks.test"
]

[[payload.kubevirt-ssp-operator-rhel9-container.ignore]]
error = "ErrGoNotCgoEnabled"
files = [
  "/usr/bin/ssp-operator.test"
]

[[payload.kubevirt-tekton-tasks-operator-rhel9-container.ignore]]
error = "ErrGoNotCgoEnabled"
files = [
  "/usr/bin/tekton-tasks-operator.test"
]

2024-12-23 15:40 UTC, ashwindasr commented
/uncc @ashwindasr 
/cc @rhmdnd

2025-01-02 14:14 UTC, rhmdnd commented
Thanks @tal-hason,

Was there some restructuring in the upstream repository that requires this change? I'm missing some context around why this is required.

2025-01-02 14:22 UTC, tal-hason commented
> Thanks @tal-hason,
> 
> Was there some restructuring in the upstream repository that requires this change? I'm missing some context around why this is required.

i got a message from @asergienk in this slack:
https://redhat-internal.slack.com/archives/C07TC0L7ATB/p1734712782375279?thread_ts=1731412943.825689&cid=C07TC0L7ATB

to update the changes

2025-01-08 13:13 UTC, rhmdnd commented on dist/releases/4.13/config.toml
> -[[payload.multicluster-engine-hypershift-operator-container.ignore]]
Was this bit intentional? We just landed a PR to add these exceptions yesterday.

https://github.com/openshift/check-payload/pull/230/files

2025-01-08 13:14 UTC, rhmdnd reviewed
The additions look good, just one comment on if we're supposed to be removing the mce exception or not (that seems orthogonal?).

2025-01-08 13:24 UTC, tal-hason commented on dist/releases/4.13/config.toml
> -[[payload.multicluster-engine-hypershift-operator-container.ignore]]
i did not know, if the change would affect our files so don't care

2025-01-08 14:20 UTC, rhmdnd requested changes

2025-01-08 14:20 UTC, rhmdnd commented on dist/releases/4.13/config.toml
> -[[payload.multicluster-engine-hypershift-operator-container.ignore]]
Removing these exceptions will affect other projects, and reintroduce a FIPS error they just fixed.

https://github.com/openshift/check-payload/pull/230

2025-01-08 14:32 UTC, tal-hason commented on dist/releases/4.13/config.toml
> -[[payload.multicluster-engine-hypershift-operator-container.ignore]]
i guess this is why i got a Conflict yesterday.

2025-01-08 19:20 UTC, rhmdnd requested changes
One more comment on the MCE changes.

It looks like this change is necessary, in part, because the majority of the files that needed to be excluded were in `kubevirt-tekton-tasks-operator-rhel9-container`, but that's been broken up into other container images.

2025-01-08 19:20 UTC, rhmdnd commented on dist/releases/4.13/config.toml
> -[[payload.multicluster-engine-hypershift-operator-container.ignore]]
> i guess this is why i got a Conflict yesterday.

Yeah, I imagine so.

I don't think we need to duplicate the ignore logic from lines 99-104. The only difference between the two are the files being ignored, and check-payload's configuration is built to accept multiple files for the same component with the same error.

https://github.com/openshift/check-payload/blob/main/internal/types/types_config.go#L15-L23

We should be able to leave the `multicluster-engine-hypershift-operator-container` section as-is.

2025-01-08 19:20 UTC, rhmdnd commented on dist/releases/4.18/config.toml
> +files = ["/usr/bin/hcp-no-cgo"]
Same comment here as above.

2025-01-09 09:02 UTC, tal-hason commented on dist/releases/4.18/config.toml
> +files = ["/usr/bin/hcp-no-cgo"]
So, you want me to revert this change?

2025-01-09 12:59 UTC, rhmdnd commented on dist/releases/4.18/config.toml
> +files = ["/usr/bin/hcp-no-cgo"]
These specific lines, yes, since the config syntax here should work well as-is.

2025-01-09 13:57 UTC, tal-hason commented
> One more comment on the MCE changes.
> 
> It looks like this change is necessary, in part, because the majority of the files that needed to be excluded were in `kubevirt-tekton-tasks-operator-rhel9-container`, but that's been broken up into other container images.

changed as requested

2025-01-20 09:56 UTC, Axuba commented
Is anything blocking this PR getting merged? @rhmdnd

2025-01-26 19:48 UTC, tal-hason commented
Hi @rhmdnd are we going to merge this by the end of the week? The due date is coming, thanks

2025-01-30 14:11 UTC, rhmdnd approved these changes
/lgtm

Thanks for isolating the changes.

2025-01-30 14:55 UTC, merged